rewrite:icetool

diff --git a/extra/system/bin/icetool b/extra/system/bin/icetool
--- a/extra/system/bin/icetool
+++ b/extra/system/bin/icetool
@@ -1,161 +1,196 @@
 #!/system/xbin/bash
-WHO=`whoami`
-if [ "$WHO" != "root" ]; then
-  echo "Must be root"
-  exit 1
-fi
 
-if [ "$1" = "" ]; then
-  echo "Usage: $0 <cmd> ..."
-  exit 2
-fi
+# modify by ac1965 AT gmail DOT com
+# original from git://github.com/alienmind/ICEDroid.git
 
-CMD=$1
+set -e
 
-Remount() {
-  local MODE=$1
-  mount -o remount,$MODE /system
+declare -A CMD=(\
+  [help]="This Messages" \
+	[reboot]="Reboot phone" \
+	[fastchargeon]="High power charging Enabled" \
+	[fastchargeoff]="High power charging Disabled" \
+	[remountsysrw]="/system remount read-write" \
+	[remountsysro]="/system remount read-only" \
+	[chargedisable]="Charge on plug Disabled" \
+	[chargeenable]="Charge on plug Enabled" \
+	[market]="Other Version Market Apply" \
+	[gpsconf]="GPS Configuration" \
+	[dspinit]="DSP Profile Configuration" \
+	[ril]="RIL Switch and Reboot" \
+	[density]="Density Configuration" \
+)
+
+
+die () {
+	echo "$1"
+	exit 1
 }
 
-Reboot() {
-  local PAUSE=$1
-  printf "Syncing...\n"
-  sync ; sync ; sync
-  printf "Rebooting in $PAUSE seconds...\n"
-  for i in `seq 1 $PAUSE`; do
-    printf "%d." $i
-    sleep 1
-  done
-  printf "\n"
-  reboot
+Remount () {
+	local mode=$1
+	mount -o remount,$mode /system
 }
 
-InstallMarket() {
-  local APK=$1
-  Remount "rw"
-  pm uninstall com.android.vending
-  rm -f /data/app/com.android.vending*apk
-  cp $APK /system/app/Vending.apk
-  chmod 644 /system/app/Vending.apk
-  pm install $APK
-  Remount "ro"
+Reboot () {
+	local grace_time=$1
+	printf "Syncing...\n"
+	sync;sync;sync
+	printf "Rebooting in $grace_time seconds...\n"
+	for i in $(seq 1 $grace_time)
+	do
+		printf "%d." $i
+	done
+	printf "\n"
+	reboot
 }
 
-LaunchMarket() {
-  am start -a android.intent.action.MAIN -n com.android.vending/com.android.vending.AssetBrowserActivity
+InstallMartet () {
+	local APK=$1
+	local APPF="/system/app/Vending.apk"
+	Remount "rw"
+	pm uninstall com.android.vending
+	rm -f /data/app/com.android.venging*apk
+	cp $APK $APPF
+	chmod 644 $APPF
+	pm install $APPF
+	Remount "ro"
 }
 
-###
-# Internal commands
-#
-# fastchargeon
-if [ "$CMD" = "fastchargeon" ]; then
-  echo "1" > /sys/class/power_supply/battery/force_high_power_charging
-  echo "High power charging enabled"
-  exit 0
+LauncherMarket () {
+	am start -a android.intent.action.MAIN \
+		-n com.android.vending/com.android.vending.AssetBrowserActivity
+}
 
-###
-# fastchargeoff
-elif [ "$CMD" = "fastchargeoff" ]; then
-  echo "0" > /sys/class/power_supply/battery/force_high_power_charging
-  echo "High power charging disabled"
+fastchageron () {
+	echo "1" > /sys/class/power_supply/battery/force_high_power_charging
+	echo "High power charging enabled"
+}
 
-###
-# remountsysrw
-elif [ "$CMD" = "remountsysrw" ]; then
-  Remount "rw"
-  mount | grep system
-  echo "/system remounted read/write"
+fastchageroff () {
+	echo "0" > /sys/class/power_supply/battery/force_high_power_charging
+	echo "High power charging disabled"
+}
 
-###
-# remountsysro
-elif [ "$CMD" = "remountsysro" ]; then
-  Remount "ro"
-  mount | grep system
-  echo "/system remounted read-only"
+remountstatus () {
+	local MODE=$1
+	local MESSG=$2
+	Remount $MODE
+	mount | grep system | grep "${MODE}"
+	case "$?" in
+		0) echo "$2";;
+	esac
+}
 
-###
-# chargedisable
-elif [ "$CMD" = "chargedisable" ]; then
-  echo "0" > /sys/devices/platform/rs30100001:00000000/power_supply/battery/charge_on_plug_enabled
-  echo "Charge on plug disabled - unplug/plug to make it work"
+charge () {
+	local VALUE=$1
+	local MESSG=$2
+	echo $VALUE > /sys/devices/platform/rs30100001:00000000/power_supply/battery/charge_on_plug_enabled
+	echo "$MESSG"
+}
 
-###
-# chargeenable
-elif [ "$CMD" = "chargeenable" ]; then
-  echo "1" > /sys/devices/platform/rs30100001:00000000/power_supply/battery/charge_on_plug_enabled
-  echo "Charge on plug enabled - unplug/plug to make it work"
+market () {
+	local VER=$1
+        APK=/sdcard/market/Vending-${VER}.apk
+  	if [ -f $APK ]; then
+    		InstallMarket $APK
+    		LaunchMarket
+    		echo "Market reverted to new version"
+  	else
+    		die "Couldn't find Market version $VER" 
+  	fi
+}
 
-###
-# market
-elif [ "$CMD" = "market" ]; then
-set -x
-  VER=$2
-  APK=/sdcard/market/Vending-${VER}.apk
-  if [ -f $APK ]; then
-    InstallMarket $APK
-    LaunchMarket
-    echo "Market reverted to new version"
-  else
-    echo "Couldn't find Market version $VER" 
-    exit 1
-  fi
-set +x
-###
-# gpsconf
-elif [ "$CMD" = "gpsconf" ]; then
-  ZIP=/sdcard/gpsconf/$2
-  if [ ! -f "$ZIP" ]; then
-    echo "Nonexistent $ZIP!!!"
-  else
-    Remount "rw"
-    cd /
-    unzip -o $ZIP system/etc/gps.conf
-    RET=$?
-    if [ "$RET" != "0" ]; then
-      echo "Error extracting /system/etc/gps.conf from $ZIP"
-    else
-      echo "GPS configuration for $2 applied - open GPS Status and redownload AGPS data"
-    fi
-    Remount "ro"
-  fi
+gpsconf () {
+	local F=$1
+	ZIP=/sdcard/gps/conf/$F
+	if [ -f "$ZIP" ]; then
+		Remount "rw"
+		cd /
+		unzip -o $ZIP system/etc/gps.conf
+		case "$?" in
+		0) "GPS configuration for $F applied - open GPS Status and redownload AGPS data";;
+		*) "Error extracting /system/etc/gps.conf from $ZIP";;
+		esac
+		Remount "ro"
+	else
+		echo "Nonexistent $ZIP!!!"
+	fi
+}
 
-###
-# dspchooser
-elif [ "$CMD" = "dspinit" ]; then
-    snd3254 -dspmode $2
-    echo "DSP profile for $2 applied"
+dspinit () {
+	local MODE=$1
+	snd3254 -dspmode $MODE
+	echo "DSP profile for $MODE applied"
+}
 
-###
-# ril
-elif [ "$CMD" = "ril" ]; then
-  DIR=/sdcard/ril/$2
-  if [ -d "$DIR" ]; then
-    printf "RIL before patch: "
-    getprop | grep RIL
-    Remount "rw"
-    cp -r $DIR/* /
-    Remount "ro"
-    echo "RIL switched to $2. Rebooting is highly recommended!"
-  else 
-     echo "Error: $DIR does not exist"
-     exit 1
-  fi
+ril () {
+	local DN=$1
+	DIR=/sdcard/ril/$DN
+	printf "RIL before patch: "
+	getprop | grep RIL | cut -d'[' -f3 | cut -d ']' -f1
+	test -z "$DZ" && die "Error: Please specify RIL"
+	if [ -d "$DIR" ]; then
+		Remount "rw"
+		cp -r $DIR/* /
+		Remount "ro"
+		echo "RIL switched to $DN. Rebooting is highly recommended!"
+    	else
+		die "Error: $DIR does not exist"
+	fi
+}
 
-###
-# density
-elif [ "$CMD" = "density" ]; then
-  DENSITY=$2
-  Remount "rw"
-  cat /system/build.prop |  sed "s/ro.sf.lcd_density=.*/ro.sf.lcd_density=$DENSITY/g" > /system/build.prop.new
-  mv /system/build.prop.new /system/build.prop
-  chmod 644 /system/build.prop
-  Remount "ro"
-  Reboot 5
-       
-### Any other command - we are a wrapper
-else
+density () {
+	local DENSITY=$1
+	CHAR_STOP=$(expr "$DENSITY" : '\([0-9]*\)')
+	test "$DENSITY" != "$CHAR_STOP" && die "Illegal Value : $DENSITY"
+	Remount "rw"
+  	sed -i "s/ro.sf.lcd_density=.*/ro.sf.lcd_density=$DENSITY/g" /system/build.prop
+  	Remount "ro"
+  	Reboot 5
+}
 
-  exec $@
+help () {
+	printf "Usage: $MYNAME CMD Option\n\n"
+	printf "CMD:\n"
+	for d in \
+		help \
+		reboot \
+		fastchargeon \
+		fastchargeoff \
+		remountsysrw \
+		remountsysro \
+		chargedisable \
+		chargeenable \
+		market \
+		gpsconf \
+		dspinit \
+		ril \
+		density
+	do
+		echo -e "$d\t: ${CMD[$d]}"
+	done
+	exit 0
+}
 
-fi
+test x"$(whoami)" = x"root" || die "Must be root"
+
+case "$1" in
+	reboot) Reboot 5;;
+	fastchargeron) fastchargeron;;
+	fastchargeroff) fastchargeroff;;
+	remountsysrw) remountstatus "rw" "/system remounted read-wrie";;
+	remountsysro) remountstatus "ro" "/system remounted read-only";;
+	chargedisable) charge 0 "Charge on plug disabled - unplug/plug to make it work";;
+	chargeenable) charge 1 "Charge on plug enabled - unplug/plug to make it work";;
+	market) market $2;;
+	gpsconf) gpsconf $2;;
+	dspinit) dspinit $2;;
+	ril) ril $2;;
+	density) density $2;;
+	--help|-help|-h|-?|"") help;;
+	*)
+		exec $@;;
+esac
+
+exit 0
